services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=vmldb'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=postgres'
    ports:
      - '3080:5432'
  mailpit:
    image: 'axllent/mailpit:v1.27'
    ports:
      - '127.0.0.1:1025:1025'
      - '127.0.0.1:8025:8025'
